require("theprimeagen.telescope")
require("theprimeagen.nvim-tree")
require("theprimeagen.treesitter")
require("theprimeagen.dap")
require("theprimeagen.lsp-config")
require("theprimeagen.autopairs")
